### ISSUE TITLE
Object.observe fallback

### ISSUE THREAD

**Issue by jgrund** [jeffbcross/omnibinder#16]
Is there a longer term plan or a shim that should be used for browsers that do not support Object.observe?

**Comment by daviddeutsch** [comment]
Pretty sure that's why the example includes [observe-js](https://github.com/Polymer/observe-js) :wink:

**Comment by daviddeutsch** [comment]
Nope, actually didn't see it's hardcoded. Made a PR: https://github.com/jeffbcross/omnibinder/pull/22
